basePath: /
host: localhost:8000
info:
  contact: {}
  description: API Server for BookSmart Application
  title: BookSmart API
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
