x-common-postgres: &common-postgres
  image: postgres:latest
  environment:
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_DB: ${POSTGRES_DB}
  volumes:
    - ${DB_DATASETS_PATH}:/data

x-common-redis: &common-redis
  image: redis:latest
  environment:
    REDIS_PASSWORD: ${REDIS_PASSWORD}
    REDIS_USER: ${REDIS_USER}
    REDIS_USER_PASSWORD: ${REDIS_USER_PASSWORD}
  command: >
    sh -c '
      mkdir -p /usr/local/etc/redis &&
      echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
      echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
      echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
      echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl &&
      echo "user $REDIS_USER on >$REDIS_USER_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
      redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
    '

services:
  bs-ppo-app:
    image: booksmart:local
    container_name: bs-ppo-app
    ports:
      - "${APP_PORT}:8000"
    volumes:
      - ./.logs/:/usr/local/src/logs
      - ./.env:/usr/local/src/.env
      - ./configs/config.yml:/usr/local/src/configs/config.yml
    depends_on:
      bs-ppo-postgres:
        condition: service_healthy
      bs-ppo-redis:
        condition: service_started
      bs-ppo-mongo:
        condition: service_started
    networks:
      - bs-ppo

  bs-ppo-postgres:
    <<: *common-postgres
    container_name: bs-ppo-postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
      - ${DB_DATASETS_PATH}:/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - bs-ppo

  bs-ppo-mongo:
    container_name: bs-ppo-mongo
    image: mongo:latest
    ports:
      - "${MONGO_DB_PORT}:27017"
    volumes:
      - ${MONGO_MIGRATION_PATH}/rs-initiate.js:/docker-entrypoint-initdb.d/rs-initiate.js
      - ./.data/mongo/:/data/db/
    command: [ "--replSet", "dbrs-ppo", "--bind_ip_all" ]
    networks:
      - bs-ppo

  bs-ppo-redis:
    <<: *common-redis
    container_name: bs-ppo-redis
    volumes:
      - ./.data/redis:/var/lib/redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - bs-ppo

  bs-ppo-postgres-test:
    <<: *common-postgres
    container_name: bs-ppo-postgres-test
    ports:
      - "${POSTGRES_PORT_TEST}:5432"
    volumes:
      - ./.data/postgresTest:/var/lib/postgresql/data
      - ${DB_DATASETS_PATH}:/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - bs-ppo-test

  bs-ppo-redis-test:
    <<: *common-redis
    container_name: bs-ppo-redis-test
    volumes:
      - ./.data/redisTest:/var/lib/redis
    ports:
      - "${REDIS_PORT_TEST}:6379"
    networks:
      - bs-ppo-test


networks:
  bs-ppo:
    driver: bridge
  bs-ppo-test:
    driver: bridge