// Code generated by MockGen. DO NOT EDIT.
// Source: ITransactionManager.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockITransactionManager is a mock of ITransactionManager interface.
type MockITransactionManager struct {
	ctrl     *gomock.Controller
	recorder *MockITransactionManagerMockRecorder
}

// MockITransactionManagerMockRecorder is the mock recorder for MockITransactionManager.
type MockITransactionManagerMockRecorder struct {
	mock *MockITransactionManager
}

// NewMockITransactionManager creates a new mock instance.
func NewMockITransactionManager(ctrl *gomock.Controller) *MockITransactionManager {
	mock := &MockITransactionManager{ctrl: ctrl}
	mock.recorder = &MockITransactionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITransactionManager) EXPECT() *MockITransactionManagerMockRecorder {
	return m.recorder
}

// WithTransaction mocks base method.
func (m *MockITransactionManager) WithTransaction(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockITransactionManagerMockRecorder) WithTransaction(ctx, fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockITransactionManager)(nil).WithTransaction), ctx, fn)
}
