x-common-postgres: &common-postgres
  image: postgres:latest
  environment:
    POSTGRES_USER: ${POSTGRES_DB_USER}
    POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
    POSTGRES_DB: ${POSTGRES_DB_NAME}
  volumes:
    - ${DB_DATASETS_PATH}:/data

x-common-redis: &common-redis
  image: redis:latest
  environment:
    REDIS_PASSWORD: ${REDIS_PASSWORD}
    REDIS_USER: ${REDIS_USER}
    REDIS_USER_PASSWORD: ${REDIS_USER_PASSWORD}
  command: >
    sh -c '
      mkdir -p /usr/local/etc/redis &&
      echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
      echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
      echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
      echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl &&
      echo "user $REDIS_USER on >$REDIS_USER_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
      redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
    '
services:
  test-postgres-db:
    <<: *common-postgres
    container_name: test_postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME_TEST}
    ports:
      - "${POSTGRES_DB_PORT_TEST}:5432"

  test-redis:
    <<: *common-redis
    container_name: test_redis
    ports:
      - "${REDIS_PORT_TEST}:6379"

  postgres-db:
    <<: *common-postgres
    container_name: postgres_db
    ports:
      - "${POSTGRES_DB_PORT}:5432"

  redis:
    <<: *common-redis
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"

  mongo-db:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    ports:
      - '${MONGO_DB_PORT}:27017'

  log-influxdb:
    image: influxdb:latest
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_INIT_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_INIT_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_INIT_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_INIT_BUCKET}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_INIT_ADMIN_TOKEN}
    ports:
      - "8086:8086"
