DROP TABLE IF EXISTS bs.reservation;
DROP TABLE IF EXISTS bs.favorite_books;
DROP TABLE IF EXISTS bs.lib_card;
DROP TABLE IF EXISTS bs.reader;
DROP TABLE IF EXISTS bs.book;

DROP TYPE BOOK_RARITY;
DROP TYPE RESERVATION_STATE;
DROP TYPE READER_ROLE;